== Module 5: Using OpenShift Telemetry
:navtitle: Using OpenShift Telemetry

We will explore the *Kubernetes Sidecar* design pattern, which deploys an agent sidecar container within an application pod that sends traces to a centralized Grafana Tempo. 

The application will send tracing data to a *collector agent* (sidecar), which offloads responsibility by forwarding the data to a storage backend—in this case, the central Grafana Tempo instance.

== Instrumentation

*Instrumentation* is the process of adding observability code to an application.  
*Auto instrumentation* sets up this tracing framework with minimal code changes by automatically injecting and configuring instrumentation libraries in various supported languages.

For example, auto instrumentation of .NET sends data on port `4318` using the `OTLP/HTTP` protocol.

== Git Repositories

*Python:* https://github.com/pkredhat/nb-workshop/tree/module5-python  

== Objectives

Inside your workspace is a Python application that listens on `/api/check` for web requests and returns an HTTP `200` or `500` status code based on the payload.

From the Terminal, deploy the Python Application in your project using:

[source,sh]
----
oc new-build --binary --name nb-workshop-<your username>
oc start-build nb-workshop-<your username> --from-dir=. 
oc new-app nb-workshop-<your username> --name nb-workshop-<your username>
----

[NOTE]
====
Please ensure your application name is unique from others in the workshop. Otherwise, you may not be able to find your web requests in the Jaeger UI.
====

== Guided Exercise

. Deploy the sidecar with the OpenTelemetry Collector sidecar manifest:
+
[source,sh]
----
oc apply -f manifests/sidecar.yaml
----
+
. Create an *Instrumentation* manifest in your project to be used by the OpenTelemetry Operator:
+
[source,sh]
----
oc apply -f manifests/instrumentation.yaml
----
+
. Edit your deployment to add annotations for .NET auto instrumentation:
+
[source,sh]
----
oc edit deployment nb-workshop-<your username>
----
+
. Add the following under `spec.template.metadata.annotations`:
+
[source,yaml]
----
spec:
  template:
    metadata:
      annotations:
        ..
        instrumentation.opentelemetry.io/inject-python: "true"
        sidecar.opentelemetry.io/inject: sidecar
----

== Self-Paced Exercise

The application has some problems that we would like you to fix:

. There is a cronjob located at `curl-cron/cronjob.yaml` that will poll the application at service port `5000` every minute.

. Modify the environment variable `ENDPOINT` to match your service name `nb-workshop-<your username>` and deploy it:
+
[source,sh]
----
oc apply -f curl-cron/cronjob.yaml
----
+
[NOTE]
====
The cron job sends a request once per minute, so there might be a delay before seeing web requests in the Jaeger UI.  
You will also see requests from other users.
====
+
. A centralized Grafana Tempo instance has been deployed for the workshop. To view web requests, navigate to the OpenShift web console → *Application Menu* → *Jaeger UI*  
or open:  
https://tempo-sample-query-frontend-observability.apps.nb-demo-01.6jz4.p1.openshiftapps.com/

. The cron job is currently returning an HTTP `500`. Fix the application so that it returns an HTTP `200`.
. (Optional) To generate additional traffic without waiting for the cron job, run the following script in your Dev Spaces terminal:
+
[source,sh]
----
sh traffic-generator.sh nb-workshop-<your username>:5000
----
+
. You can trigger a new build of your application with:
+
[source,sh]
----
oc start-build nb-workshop-<your username> --from-dir=.
----

== Easter Eggs!

* There is an easter egg in the code.
* Be thorough! Look through the code.

== Takeaways

* Explored Kubernetes Sidecar design pattern  
* Auto-instrumented an application to collect tracing data  
* Generated application traffic to produce tracing data  
* Used tracing data to troubleshoot the application  
