== Module 5: Deploying the Application
:navtitle: Deploying the Application

GIT Repository: https://github.com/pkredhat/nb-workshop/tree/module5-python

Inside your workspace is a Python Application that listens at `/api/check` for web requests and returns an HTTP 200 or 500 status code based on the payload.

== Deploying the Application

From the Terminal, deploy the Python Application in your project using:

[source,sh]
----
oc new-build --binary --name nb-workshop-<your username>
oc start-build nb-workshop-<your username> --from-dir=.
oc new-app nb-workshop-<your username> --name nb-workshop-<your username>
----

[NOTE]
====
Please keep your application name unique from others in the workshop, otherwise you won’t be able to find your web requests in Jaeger UI.
====

== Configuring OpenTelemetry

We will explore the *Kubernetes Sidecar* design pattern which deploys an agent sidecar container within an application pod that sends traces to a centralized Grafana Tempo. The application will send tracing data to a collector agent (sidecar) that offloads responsibility by sending the data to a storage backend—in our case, the central Grafana Tempo instance.

Deploy the sidecar with the `sidecar.yaml` manifest:

[source,sh]
----
oc apply -f manifests/sidecar.yaml
----

Instrumentation is the process of adding observability code to an application. *Auto instrumentation* creates this tracing framework without significant code changes by automatically injecting and configuring auto-instrumentation libraries in a variety of supported languages.

Auto instrumentation of .NET sends data on port `4318` via the OTLP/HTTP protocol.

Create an Instrumentation manifest (`instrumentation.yaml`) in the project that will be used by the OpenTelemetry operator:

[source,sh]
----
oc apply -f manifests/instrumentation.yaml
----

Configure your deployment with annotations for .NET auto instrumentation:

[source,sh]
----
oc edit deployment nb-workshop-<your username>
----

[source,yaml]
----
spec:
  template:
    metadata:
      annotations:
        ..
        instrumentation.opentelemetry.io/inject-python: "true"
        sidecar.opentelemetry.io/inject: sidecar
----

== Fixing the Application

The application has some problems that we would like you to fix:

There is a cronjob at `curl-cron/cronjob.yaml` that will poll the application at service port 5000 every minute.  
Modify the environment variable `ENDPOINT` to match the service name `nb-workshop-<your username>` and deploy it:

[source,sh]
----
oc apply -f curl-cron/cronjob.yaml
----

[NOTE]
====
The cronjob sends a request once a minute, so there may be a delay in viewing the web requests in Jaeger. You will also see other users’ requests.
====

A centralized Grafana Tempo instance has been deployed for the workshop.  
In OpenShift web console, navigate to the Applications Menu → *Jaeger UI* to view the web requests.

https://tempo-sample-query-frontend-observability.apps.nb-demo-01.6jz4.p1.openshiftapps.com/

The cronjob polling the application returns an HTTP 500.  
Fix the application so that it returns HTTP 200.

== Optional: Generate Additional Traffic

To generate additional web traffic, without waiting 1 minute for the cronjob to kickoff, you can use a shell script that randomly generates 20 HTTP POST requests to your service.  
To run this in the terminal of your Dev Space:

[source,sh]
----
sh traffic-generator.sh nb-workshop-<your username>:5000
----

== Rebuilding the Application

You can create a new build of the application with the following command:

[source,sh]
----
oc start-build nb-workshop-<your username> --from-dir=.
----
